NCTU-SYNC/sync-frontend

src/components/ComparisonBlock.vue
src/views/EditComparison.vue

- handle link differences
- refactor `compareContent` function in `EditComparison.vue`

Feat/edit comparison 

---

src/views/Article.vue

Updated Article page subscribed icon with new icon.

[SYNC-21]: Applied article subscribed icon to article page

---

package.json

- fix semantic versioning in package.json
- "develop/0.1.0" -> "0.1.0"

[HotFix] Versioning

---

src/views/EditComparison.vue
src/views/History.vue

-Update article version page. 
-When users hover the row, there will be a blue token in front of the date.
-When users hover the article links, the row of corresponding article will be highlighted.
-In the comparison page, there is a blue token in front of the title of the article that was hovered by the user.
-History.vue: Add 5 methods.  historyShowCount is fixed to 20.
-EditComparison.vue: Adjust the time order of the articles.
-

[SYNC-10] feat: Update article version page

---

src/views/Profile.vue

- showing personal status display without showing email
- Remove email
- Refactor with grid
-

[SYNC-41] Update Personal Status Display

---

.env
.env.development
package.json
src/App.vue
src/components/Editor/MenuBar.vue
src/components/Editor/Modals/CitationModal.vue
src/components/Editor/Modals/LinkModal.vue
src/components/Editor/Modals/UploadImageModal.vue
src/components/Editor/TiptapEditor.vue
src/views/new/Post.vue
yarn.lock

- create modal to add link and add citation in Editor

[SYNC-33]: feat: create link and citation from modal

---

src/components/Editor/Modals/CitationModal.vue
src/components/Editor/Modals/LinkModal.vue
src/components/Editor/Modals/UploadImageModal.vue
src/components/Editor/TiptapEditor.vue

- Fix duplicated modals when there are multiple blocks
- Modify footer title in modal

[SYNC-59] [FE] Fix duplicated modals issue

---

src/views/Article.vue

- When an article has too many authors, the author field would eventually overflow and cause button displacement.
- Modify code to meet UI/UX team design
- Article page will show at most 3 authors only
- 
- Before
- After

[SYNC-58][FE] Fix reading page author overflowing issue

---

src/store/article.js

- After login it will take about 30 sec to 5 min to initialize VIEW.
- Set a sec timeout in INITIALIZE action waiting for token to be established in vuex. Then, dispatch again.

[FE][SYNC-61] 🐛 Fix it takes amount of time to initialize app

---

src/views/Home.vue

- Getting article numbers more than array length would result in an error
- Pass in Math.min(number, array.length)
- None

[SYNC-63][FE] Fix getRandomArticles() out of bound error

---

src/views/Profile.vue

- as the title suggest
- remove all CSS background icons
- display icons using img tag
- ✅ Success

[HotFix][FE]🏗 Showing icon using <img> instead of CSS background

---

src/components/Editor/Modals/UploadImageModal.vue

- Image upload modal style needs some modification
- Restyle image upload modal to match UI/UX team design
- Disable drag and drop tab
- Change `<b-nav>` to `<b-tabs>`
- None
- Insert by link:
- Insert by upload (when not disabled):

[SYNC-65][FE] Restyle image upload modal

---

src/components/NewsPanel.vue

- avoid user to re-"search" while loading news from backend
- add condition if it's loading
- turn input box readonly when loading
✅ Success

 @newb1er [SYNC-54][FE] 🐛 avoid re-submit while loading news 

---

src/App.vue
src/components/Editor/MenuCommands/AddLinkCommandButton.vue
src/components/Editor/Modals/UploadImageModal.vue
src/components/History/ComparisonBlock.vue
src/components/NavBar.vue
src/components/Post/BlockEditor.vue
src/store/article.js
src/store/post.js
src/store/user.js
src/utils/firebase.js
src/utils/request.js
src/views/Article.vue
src/views/EditComparison.vue
src/views/History.vue
src/views/NewsPanel.vue
src/views/new/Article.vue
src/views/new/Home.vue
src/views/new/Revision.vue
src/views/new/Search.vue
src/views/new/SignUp.vue

_**Please** delete unused console.log every time **before you post PR**, leaving a clean workspace for everyone 😉_
- remove all console.log
- those for outputting error messages use console.error instead
✅ Success

🔇 remove console.log

---

src/assets/scss/custom.scss
src/assets/scss/main.scss
src/views/new/Post.vue

- The UI/UX team has updated the style of the category dropdown on the Edit page
- Updated the styles
-
- No category chosen
- Category chosen
- The box shadow of the dropdown seems to appear only when I clicked the mouse, any ideas why?

[SYNC-79][Post] Style Category dropdown

---

src/components/Editor/Tag.vue
src/store/post.js
src/views/new/Post.vue

- Updated tag styles and edit feature
- Add a new `Tag.vue` component
- Make tags editable by using contenteditable
- Prevent tags from overflowing parent container
- Tags will wrap from now on
-

[SYNC-78] feat: Update tag styles and edit feature

---

src/components/ArticleCard.vue
src/components/Post/NavBarPost.vue
src/router/index.js
src/store/article.js
src/store/index.js
src/store/user.js
src/utils/auth.js
src/utils/firebase.js
src/views/Article.vue
src/views/Profile.vue
src/views/new/Article.vue
src/views/new/Post.vue

- call "user/refreshToken" action every time before sending token
- add "expirationTime" in needed
- add "user/refreshToken" action. call firebase api getIdToken() and update "user/token"
- reduce expiration time to 30 minutes
✅

[SYNC-154][FE] Refresh token every time.

---

src/components/ArticleCard.vue

- Subscribe button won't update properly whenever component re-render
- Use computed property on 'isSubscribed' variable instead of watch property
- Use javascript Array.prototype.some() instead of Array.prototype.findIndex()
✅

[SYNC-164][FE] article card: subscribe button is not displayed properly

---

src/api/user.js
src/components/Profile/PreferenceItem.vue
src/components/Profile/Setting.vue
src/store/user.js
src/utils/firebase.js

- Make options in setting page work. Pass data to backend.
- Add Timestamp array in Firestore when changing name.
- Disable button when user has changed name twice in a month.
- Pass references settings as json to Firestore.
✅

[SYNC-166][FE] Pass user's settings to backend

---

src/components/Post/NewsCard.vue

- fix incompatible problem with current citation management when importing news
- remove deprecated code
- dispatch ADD_EDITOR_CITATION action when importing news
✅

[HOTFIX] critical bug: fail to add citation when importing news

---

src/components/Headline.vue
src/router/index.js
src/views/Article.vue
src/views/new/Hashtag.vue

- Implement hashtag page
- Add link for the hashtags in an article
- http://localhost:8081/#/hashtag?q={hashtag}

[SYNC-207][FE] Add hashtag page
